# numpy的使用

In [1]:
import numpy as np

### 基本操作

### 创建numpy数组

In [293]:
a = np.ones((2,3),dtype=np.uint8)
print(a)
a = np.arange(12).reshape(2,2,3)
print(a)
b = np.zeros_like(a)
print(b)
b = np.eye(2)
print(b)
b = np.ones(2)
b = np.full([2,2],10)
b = np.linspace(-3, 3, 10)
print(b)

[[1 1 1]
 [1 1 1]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[1. 0.]
 [0. 1.]]
[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]


In [201]:
b = a[:,0,:]
print(b)
b[0] = 10
print(a)
m = {10:100,2:200,3:10,4:1,5:12,6:11,7:12,8:10,9:20,11:19}
b=np.vectorize(m.get)(a)
np.vectorize(lambda x : x+1)(a.astype(np.int32))
print(a.shape)
c=np.clip(a,a_min=None,a_max=9)
d=a.clip(min=5)
print(c)
e = a[:,0]
print(e.flags['C_CONTIGUOUS'])
ce = np.ascontiguousarray(e)
print(ce.flags['C_CONTIGUOUS'])

[[10 10 10]
 [ 6  7  8]]
[[[10 10 10]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
[[[9 9 9]
  [3 4 5]]

 [[6 7 8]
  [9 9 9]]]
False
True


### numpy中flatten和ravel都能够把多维数组降为1维，但ravel返回视图，而flatten返回拷贝。

In [91]:
a = np.arange(10)
b = np.zeros((10,3))
b.flat[a*3]=1
print(b)
c = b.flatten('F')
print(c.shape)
b.ravel()

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(30,)


array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.])

### 使用transpose和swapaxis对维度进行交换

In [30]:
a = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(a,a.shape)
b = a.swapaxes(1,2)
c = b.swapaxes(0,1)
print(c,c.shape)
d = a.transpose([2,0,1])
print(d,d.shape)
##左侧增加一个维度
e = a[None,]
print(e.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] (2, 3, 1)
[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
(1, 2, 3, 1)


### numpy随机相关

In [267]:
a = np.random.randint(0,2,[2,3])
print(a)
##gaussian
a = np.random.randn(2,2)
a = 3 * np.random.randn(2,2) + 2
a = np.random.standard_normal([2,2])
## 0~1
a = np.random.random_sample([2,2,2])
print(a)
np.random.shuffle(a)
print(a)
a = np.arange(5)
b = np.arange(5)
perm = np.arange(5)
np.random.shuffle(perm)
a = a[perm]
b = b[perm]
print(a,b)
c = np.random.uniform(-1., 1., size=[2, 5])
print(c)

[[1 0 0]
 [1 0 0]]
[[[0.53362341 0.79248762]
  [0.9102427  0.91800439]]

 [[0.36915067 0.94053301]
  [0.05072342 0.25886202]]]
[[[0.53362341 0.79248762]
  [0.9102427  0.91800439]]

 [[0.36915067 0.94053301]
  [0.05072342 0.25886202]]]
[4 2 1 0 3] [4 2 1 0 3]
[[-0.60815234  0.40022439 -0.38392822  0.54797061 -0.78303625]
 [ 0.63504974  0.93547973  0.17042041 -0.98181055  0.76047301]]


### 维度相关处理

In [288]:
a = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(a.shape)
print(a[None].shape)
print(np.squeeze(a[None]).shape)
a = np.expand_dims(a,0)
a = np.append(1-a,a,axis=0)
b = np.concatenate((np.arange(24).reshape([2,3,4]),np.arange(24).reshape([2,3,4])),axis=2)
c = np.stack((np.arange(24).reshape([2,3,4]),np.arange(24).reshape([2,3,4])),axis=2)
print(b.shape,c.shape)
a = np.roll(a,2,axis=-2)
print(a)

(2, 3, 1)
(1, 2, 3, 1)
(2, 3)
(2, 3, 8) (2, 3, 2, 4)
[[[[-1]
   [-2]
   [ 0]]

  [[-4]
   [-5]
   [-3]]]


 [[[ 2]
   [ 3]
   [ 1]]

  [[ 5]
   [ 6]
   [ 4]]]]


### 使用roll进行某一维度移动

In [51]:
a = np.arange(24).reshape(1,2,3,4)
print(a.shape)
print(np.roll(a,1,axis=1))
print(np.rollaxis(a,axis=3).shape)
print(np.moveaxis(a,source=1,destination=3).shape)

(1, 2, 3, 4)
[[[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]]
(4, 1, 2, 3)
(1, 3, 4, 2)


### 保存和读取numpy数组